### ユーザー情報取得
GET http://localhost:8000/api/users/2
Accept: application/json
Authorization: Bearer 5|3msODJmveyLNl0vEar7gZb1qjBsvrtstonJ6awiwc1a09e7f

### 指定範囲のレベル
GET http://localhost:8000/api/users/index?min_level=5&max_level=25
Accept: application/json

### 指定したユーザーIDの所持アイテム情報を取得
GET http://localhost:8000/api/users/items/1
Accept: application/json

### 指定したユーザーIDのフォローリストを取得
GET http://localhost:8000/api/users/follows/1
Accept: application/json

### 指定したユーザーIDのプロフィール情報を取得
GET http://localhost:8000/api/users/summary/8
Accept: application/json

### 指定したユーザーIDのプロフィール情報を取得
GET https://api-shot.japaneast.cloudapp.azure.com/api/users/summary/20
Accept: application/json

### 全アイテムのリスト取得
GET http://localhost:8000/api/items/index
Accept: application/json

### メールの全マスターデータを取得
GET http://localhost:8000/api/mails/index
Accept: application/json

### 指定したユーザーの受信メールを取得
GET http://localhost:8000/api/mails/receive/1
Accept: application/json

### ノーマルステージデータ取得API
GET http://localhost:8000/api/stages/normal
Accept: application/json

### 指定IDのクリエイトステージを取得
GET http://localhost:8000/api/stages/create/12
Accept: application/json

### 指定ユーザーのクリエイトステージを取得
GET http://localhost:8000/api/stages/create/user/1
Accept: application/json

### フォローユーザーのクリエイトステージを取得
GET http://localhost:8000/api/stages/create/follow/1
Accept: application/json

### イイネが多い順で30件取得
GET http://localhost:8000/api/stages/create/good
Accept: application/json

### フォローが共有したクリエイトデータを30件取得
GET http://localhost:8000/api/stages/create/share/2
Accept: application/json

### ランダム取得
GET http://localhost:8000/api/users/random/3
Accept: application/json

### ユーザー登録
POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "test"
}

### ユーザー情報の更新
POST http://localhost:8000/api/users/update
Content-Type: application/json
Accept: application/json

{
    "user_id": 151,
    "level": 999
}

### フォロー登録処理
POST http://localhost:8000/api/users/follows/store
Content-Type: application/json
Accept: application/json

{
    "user_id": 1,
    "follow_id": 2
}

### フォロー解除処理
POST http://localhost:8000/api/users/follows/destroy
Content-Type: application/json
Accept: application/json

{
    "user_id": 1,
    "follow_id": 2
}

### 所持アイテムの更新
POST http://localhost:8000/api/users/items/update
Content-Type: application/json
Accept: application/json

{
    "user_id": 100,
    "item_id": 1,
    "get_vol": 10
}

### メールの開封処理
POST http://localhost:8000/api/mails/update
Content-Type: application/json
Accept: application/json

{
    "user_id": 50,
    "mail_id": 2
}

### 共有情報登録処理
POST http://localhost:8000/api/stages/share
Content-Type: application/json
Accept: application/json

{
    "user_id": 2,
    "stage_id": 1
}

### クリエイトステージデータ登録処理
POST http://localhost:8000/api/stages/create/store
Content-Type: application/json
Accept: application/json

{
    "name": "hoge",
    "user_id": 100,
    "gimmick_pos": "{[ID:1,X:1.55f,Y:3.55f]}"
}

### クリエイトステージデータ消去処理
POST http://localhost:8000/api/stages/create/destroy
Content-Type: application/json
Accept: application/json

{
    "stage_id": 7
}

### イイネ数更新
POST http://localhost:8000/api/stages/update/good
Content-Type: application/json
Accept: application/json

{
    "id": 5,
    "good_vol": 5
}

### プレイログの登録
POST http://localhost:8000/api/stages/store/result
Content-Type: application/json
Accept: application/json

{
    "user_id": 50,
    "stage_id": 2,
    "stage_type": 1,
    "clear_flag": true
}
